safe: true

title: "The Vongott Chronicles"

url: "http://jeppezapp.com/vongott"
#url: "file:///media/jampe/Data/Work/vongott-site/build"

style: "vongott"

header: true

markdown: kramdown
